title = "TimeTracker Gitleaks Config"

[extend]
useDefault = true   # usa todas las reglas built-in de gitleaks

[allowlist]
description = "Ignorar placeholders en .env.example"
paths = [
    '''\.env\.example$'''
]