services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${UserPostgre}
      POSTGRES_PASSWORD: ${PasswordPostgre}
      POSTGRES_DB: ${DatabasePostgre}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
